const reactRules = require('./react')

module.exports = {
  ...reactRules,
  '@typescript-eslint/adjacent-overload-signatures': 0,
  '@typescript-eslint/ban-ts-comment': 0,
  '@typescript-eslint/consistent-type-imports': [1, { prefer: 'type-imports' }],
  '@typescript-eslint/explicit-function-return-type': 0,
  '@typescript-eslint/no-duplicate-enum-values': 1,
  '@typescript-eslint/no-floating-promises': 0,
  '@typescript-eslint/no-inferrable-types': 1,
  '@typescript-eslint/no-namespace': 1,
  '@typescript-eslint/no-non-null-assertion': 0,
  '@typescript-eslint/no-unnecessary-qualifier': 1,
  '@typescript-eslint/no-unnecessary-type-arguments': 1,
  '@typescript-eslint/no-unsafe-argument': 0,
  '@typescript-eslint/no-unsafe-assignment': 0,
  '@typescript-eslint/no-unsafe-call': 0,
  '@typescript-eslint/no-unsafe-member-access': 0,
  '@typescript-eslint/no-unsafe-return': 0,
  '@typescript-eslint/no-useless-empty-export': 1,
  '@typescript-eslint/no-var-requires': 0,
  '@typescript-eslint/prefer-nullish-coalescing': [
    1,
    { ignoreTernaryTests: false },
  ],
  '@typescript-eslint/prefer-optional-chain': 1,
  '@typescript-eslint/prefer-string-starts-ends-with': 1,
  '@typescript-eslint/require-array-sort-compare': 0,
  '@typescript-eslint/restrict-template-expressions': 0,
  '@typescript-eslint/strict-boolean-expressions': 0,
  '@typescript-eslint/no-empty-function': 0,
  '@typescript-eslint/no-use-before-define': 0,
}
